# Generated by Django 5.2.9 on 2025-12-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carbs', 'Carbohydrates'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('fats', 'Fats & Oils'), ('grains', 'Grains'), ('nuts', 'Nuts & Seeds'), ('other', 'Other')], max_length=20)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.URLField(blank=True)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_vegan', models.BooleanField(default=False)),
                ('common_allergens', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('ai_description', models.TextField(help_text='AI-generated description of the plan')),
                ('total_calories', models.PositiveIntegerField()),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_plans', to='profiles.dietgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('ai_description', models.TextField(help_text='AI-generated meal description')),
                ('preparation_notes', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diet.dietplan')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan_items', to='diet.ingredient')),
            ],
            options={
                'db_table': 'diet_plan_items',
                'ordering': ['meal_type', 'order_index'],
            },
        ),
    ]
